name: Atualizar Noticias BrasilViral

# Gatilhos: a cada 1 hora ou manualmente
on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora (no minuto 0)
  workflow_dispatch: # Permite execução manual

jobs:
  atualizar-noticias:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Use uma versão compatível

      # 3. Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pillow torch diffusers together transformers accelerate

      # 4. Executar news_research_agent.py
      - name: Executar news_research_agent.py
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }} # Chave de API como segredo
        run: |
          python scripts/news_research_agent.py
        continue-on-error: true # Continua mesmo se houver erro

      # 5. Executar indexador_de_noticias.py
      - name: Executar indexador_de_noticias.py
        run: |
          python scripts/indexador_de_noticias.py
        continue-on-error: true

      # 6. Executar news_json_generator.py
      - name: Executar news_json_generator.py
        run: |
          python scripts/news_json_generator.py
        continue-on-error: true

      # 7. Commit e push das alterações
      - name: Commit e push das alterações
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git diff --staged --quiet || git commit -m "Atualizar notícias automaticamente [GitHub Actions]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
